// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAFKzPL_Ba0K98ZbkRDyu6WjpAs77yPtU',
    appId: '1:1065551791970:web:3854a75fb7158a0abf0e3b',
    messagingSenderId: '1065551791970',
    projectId: 'finalproj-piano-game',
    authDomain: 'finalproj-piano-game.firebaseapp.com',
    storageBucket: 'finalproj-piano-game.firebasestorage.app',
    measurementId: 'G-N21H1FGQ66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7SPU51P_7G9M1IDhaXrj1PXj5CAglUbE',
    appId: '1:1065551791970:android:50070fabd967839ebf0e3b',
    messagingSenderId: '1065551791970',
    projectId: 'finalproj-piano-game',
    storageBucket: 'finalproj-piano-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4NsQL8sO8b7VpYLwevRMTKG9hg9ZT_CQ',
    appId: '1:1065551791970:ios:d5a03cef7cf0ffcdbf0e3b',
    messagingSenderId: '1065551791970',
    projectId: 'finalproj-piano-game',
    storageBucket: 'finalproj-piano-game.firebasestorage.app',
    iosBundleId: 'com.example.hiWorldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4NsQL8sO8b7VpYLwevRMTKG9hg9ZT_CQ',
    appId: '1:1065551791970:ios:d5a03cef7cf0ffcdbf0e3b',
    messagingSenderId: '1065551791970',
    projectId: 'finalproj-piano-game',
    storageBucket: 'finalproj-piano-game.firebasestorage.app',
    iosBundleId: 'com.example.hiWorldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAFKzPL_Ba0K98ZbkRDyu6WjpAs77yPtU',
    appId: '1:1065551791970:web:17f2e860ae8d3152bf0e3b',
    messagingSenderId: '1065551791970',
    projectId: 'finalproj-piano-game',
    authDomain: 'finalproj-piano-game.firebaseapp.com',
    storageBucket: 'finalproj-piano-game.firebasestorage.app',
    measurementId: 'G-3W0KKNB5YC',
  );
}
